---
# Topic: users
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: users
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 6
  kafkaClusterRef:
    name: kafka
    namespace: confluent
---
# Datagen: users
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: users
  namespace: confluent
spec:
  class: io.confluent.kafka.connect.datagen.DatagenConnector
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: users
    quickstart: users
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schemaregistry.confluent.svc.cluster.local:8081
    max.interval: "100"
    iterations: "10000000"
---
# Topic: pageviews
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 6
  kafkaClusterRef:
    name: kafka
    namespace: confluent
---
# Datagen: pageviews
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: io.confluent.kafka.connect.datagen.DatagenConnector
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: pageviews
    quickstart: pageviews
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schemaregistry.confluent.svc.cluster.local:8081
    max.interval: "100"
    iterations: "10000000"
