# Based on: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_additional_mongod_config_cr.yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: demoRole
        db: admin
        privileges:
          - resource:
              db: "local"
              collection: "" # an empty string indicates any collection
            actions:
              - find
        roles: []
  users:
    - name: demo-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: demo-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: demoRole # apply the custom role to the user
          db: local
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-user-password
type: Opaque
stringData:
  password: "1234567890"